import { loadContentPack, type ContentPack } from "../schema/content-pack.js";
import { encodeTiles, loadMap, type LunarMap, type Tile } from "../map/tiles.js";
import type { GameMap } from "../schema/items.js";

/**
 * Inline fixture content for system unit tests (sim-core tests cannot read
 * data/ from disk — that's the root-level suite's job). Values mirror the
 * base pack but are owned by the tests: tweaking game balance must not
 * silently change unit-test expectations.
 */

const AS_OF = "2026-06";

function constant(id: string, value: number, unit: string): Record<string, unknown> {
  return { id, value, unit, source: "test fixture", as_of: AS_OF };
}

export const TEST_CONSTANTS = [
  constant("day_synodic", 29.53, "Earth days"),
  constant("temp_day_max", 400, "K"),
  constant("temp_night_min", 100, "K"),
  constant("temp_psr", 40, "K"),
  constant("temp_internal_target", 295, "K"),
  constant("temp_freeze", 273, "K"),
  constant("temp_overheat", 310, "K"),
  constant("thermal_leak_kw_per_k_per_tonne", 0.00083, "kW/K per tonne"),
  constant("building_specific_heat", 1.0, "kJ/(kg*K)"),
  constant("heater_max_kw", 5, "kW"),
  constant("thermal_damage_rate_per_hour", 0.002, "condition/h"),
  constant("radiator_night_multiplier", 1.6, "factor"),
  // ── M3 crew/ECLSS/radiation/health (values mirror data/base) ──
  constant("crew_o2_day", 0.84, "kg/person/day"),
  constant("crew_co2_day", 1.0, "kg/person/day"),
  constant("crew_water_potable_day", 3.54, "kg/person/day"),
  constant("crew_hygiene_water_day", 3.5, "kg/person/day"),
  constant("crew_food_dry_day", 0.62, "kg/person/day"),
  constant("o2_reserve_target_days", 3, "days"),
  constant("co2_warning_kg_per_person", 0.5, "kg/person"),
  constant("co2_danger_kg_per_person", 1.0, "kg/person"),
  constant("co2_grace_ticks", 36, "ticks"),
  constant("co2_health_per_hour", 2, "health/h"),
  constant("hypoxia_health_per_hour", 20, "health/h"),
  constant("dehydration_health_per_day", 12, "health/day"),
  constant("starvation_health_per_day", 2.5, "health/day"),
  constant("starvation_morale_per_day", 10, "morale/day"),
  constant("radiation_sickness_health_per_day", 5, "health/day"),
  constant("bone_muscle_drift_per_month", 0.5, "health/month"),
  constant("clinic_heal_per_day", 1, "health/day"),
  constant("clinic_medkit_per_patient_day", 0.1, "medkits/patient/day"),
  constant("medical_event_rate_per_year_per_crew", 0.05, "events/crew/year"),
  constant("morale_baseline", 70, "morale"),
  constant("morale_recovery_per_day", 2, "morale/day"),
  constant("crowding_morale_per_day", 5, "morale/day"),
  constant("dose_surface_chronic", 0.5, "mSv/day"),
  constant("dose_limit_30day", 250, "mSv"),
  constant("dose_career_limit", 600, "mSv"),
  constant("spe_shelter_min", 4, "g/cm2"),
  constant("spe_shelter_safe", 10, "g/cm2"),
  // ── M4/M5 ──
  constant("construction_hours_per_tonne", 8, "h/tonne"),
  constant("dust_solar_degradation_per_eva_day", 0.005, "frac/EVA-day"),
  constant("dust_landing_spike", 0.05, "frac/landing"),
  constant("dust_pad_mitigation", 0.9, "frac removed"),
  constant("dust_cleaning_per_day", 0.01, "frac/day"),
  constant("repair_parts_kg_per_point", 200, "kg/point"),
  constant("repair_points_per_day", 0.1, "points/day"),
  constant("science_per_scientist_day", 2, "points/skill/day"),
  constant("crew_ops_usd_per_day", 100000, "USD/crew/day"),
  constant("lox_price_usd_per_kg", 2000, "USD/kg"),
  constant("lox_demand_kg_per_day", 50, "kg/day"),
  constant("night_landing_penalty", 0.05, "probability"),
  constant("sortie_stay_days", 6.5, "days"),
  constant("probe_payload_kg", 100, "kg"),
  constant("sortie_payload_kg", 5000, "kg"),
  // ── M6/M7 ──
  constant("crop_area_per_person", 45, "m2"),
  constant("immigration_wave_days", 30, "days"),
  constant("immigration_wave_size", 8, "settlers"),
  constant("birth_rate_per_year_per_10_crew", 0.5, "births/yr/10 crew"),
  constant("fresh_food_morale_bonus", 5, "morale"),
  constant("he3_price_usd_per_kg", 20000000, "USD/kg"),
  constant("he3_demand_kg_per_day", 0.01, "kg/day"),
  constant("mass_driver_demand_multiplier", 5, "factor"),
  {
    id: "vehicle_clps",
    value: {
      payloadKg: 100,
      usdPerKg: 250000,
      failureIdeal: 0.05,
      failureRealistic: 0.5,
      transitDays: 4,
    },
    unit: "composite",
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "vehicle_mid",
    value: {
      payloadKg: 1500,
      usdPerKg: 150000,
      failureIdeal: 0.03,
      failureRealistic: 0.1,
      transitDays: 4,
    },
    unit: "composite",
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "vehicle_heavy",
    value: {
      payloadKg: 12000,
      usdPerKg: 100000,
      failureIdeal: 0.02,
      failureRealistic: 0.05,
      transitDays: 4,
    },
    unit: "composite",
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "vehicle_starship",
    value: {
      payloadKg: 100000,
      usdPerKg: 10000,
      failureIdeal: 0.02,
      failureRealistic: 0.05,
      transitDays: 4,
    },
    unit: "composite",
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "radiation_shielding_curve",
    value: {
      "0": 1.0,
      "4": 0.85,
      "10": 0.7,
      "30": 0.55,
      "50": 0.5,
      "75": 0.6,
      "105": 0.5,
      "180": 0.45,
      "300": 0.35,
    },
    unit: "factor by g/cm2",
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "cost_per_kg_surface",
    value: { legacy: 1000000, clps: 250000, heavy: 100000, starshipTarget: 10000 },
    unit: "USD/kg",
    source: "test fixture",
    as_of: AS_OF,
  },
];

function building(overrides: Record<string, unknown>): Record<string, unknown> {
  return {
    name: overrides["id"],
    tier: 2,
    phase: 2,
    analogue: "test",
    source: "test fixture",
    as_of: AS_OF,
    footprint: [1, 1],
    heatKw: 0,
    priorityTier: null,
    buildCost: { imported: [], local: [] },
    placement: { terrain: ["highland", "mare"], maxSlope: 31, requiresPSR: false },
    reactions: [],
    techRequired: null,
    ...overrides,
  };
}

export const TEST_BUILDINGS = [
  building({
    id: "hab",
    massKg: 12000,
    powerKw: -6,
    heatKw: 4,
    radiatorKw: 6,
    priorityTier: 0,
    services: { housing: 4 },
    shieldingGcm2: 5,
  }),
  building({
    id: "shelter",
    massKg: 3000,
    powerKw: -0.5,
    heatKw: 0.5,
    radiatorKw: 1,
    priorityTier: 0,
    services: { shelter: 8 },
    shieldingGcm2: 10,
  }),
  building({
    id: "eclss",
    massKg: 2500,
    powerKw: -4,
    heatKw: 2,
    radiatorKw: 3,
    priorityTier: 0,
    eclss: { scrubberKgCo2Day: 8, ogaKgO2Day: 9, waterRecovery: 0.93, waterKgDay: 60 },
  }),
  building({
    id: "sabatier",
    massKg: 500,
    powerKw: -2,
    heatKw: 1,
    radiatorKw: 2,
    priorityTier: 2,
    reactions: ["r-sabatier"],
    reactionKgPerDay: { "r-sabatier": 5 },
  }),
  building({
    id: "harvester",
    crewOps: { engineer: 1 },
    massKg: 3000,
    powerKw: -15,
    heatKw: 2,
    radiatorKw: 3,
    priorityTier: 3,
    mining: { kgPerDay: 720, energyKwhPerKg: 0.5 },
    placement: { terrain: ["highland", "mare"], maxSlope: 31, requiresPSR: true },
  }),
  building({
    id: "oven",
    crewOps: { engineer: 1 },
    massKg: 2000,
    powerKw: -20,
    heatKw: 4,
    radiatorKw: 6,
    priorityTier: 3,
    reactions: ["r-ice-extraction"],
    reactionKgPerDay: { "r-ice-extraction": 320 },
  }),
  building({
    id: "electro",
    crewOps: { engineer: 1 },
    massKg: 1000,
    powerKw: -25,
    heatKw: 1.2,
    radiatorKw: 2.5,
    priorityTier: 3,
    reactions: ["r-electrolysis"],
    reactionKgPerDay: { "r-electrolysis": 106 },
  }),
  building({
    id: "cryo",
    crewOps: { engineer: 1 },
    massKg: 3000,
    powerKw: -30,
    heatKw: 6,
    radiatorKw: 9,
    priorityTier: 3,
    reactions: ["r-lox"],
    reactionKgPerDay: { "r-lox": 63 },
  }),
  building({
    id: "mre-s",
    crewOps: { engineer: 1 },
    massKg: 400,
    powerKw: -14,
    heatKw: 5,
    radiatorKw: 7,
    priorityTier: 3,
    reactions: ["r-mre"],
    reactionKgPerDay: { "r-mre": 2.74 },
  }),
  building({
    id: "printer",
    crewOps: { engineer: 1 },
    massKg: 3000,
    powerKw: -25,
    heatKw: 3,
    radiatorKw: 5,
    priorityTier: 3,
    reactions: ["r-printing"],
    reactionKgPerDay: { "r-printing": 300 },
  }),
  building({
    id: "berm",
    massKg: 20000,
    powerKw: 0,
    shieldingGcm2: 6,
    shieldingAura: true,
    buildCost: { imported: [], local: [{ resource: "regolith", kg: 20000 }] },
  }),
  building({
    id: "pad",
    massKg: 5000,
    powerKw: 0,
    landingPad: true,
    footprint: [3, 3],
    buildCost: { imported: [], local: [{ resource: "printed-structure", kg: 5000 }] },
  }),
  building({
    id: "depot",
    massKg: 2000,
    powerKw: -5,
    heatKw: 1,
    radiatorKw: 2,
    priorityTier: 3,
    propellantDepot: true,
  }),
  building({
    id: "gated",
    massKg: 1000,
    powerKw: -1,
    priorityTier: 3,
    techRequired: "t_adv",
  }),
  building({
    id: "gym",
    massKg: 1000,
    powerKw: -1,
    heatKw: 0.5,
    radiatorKw: 1,
    priorityTier: 2,
    services: { exercise: 4 },
  }),
  building({
    id: "clinic",
    massKg: 1500,
    powerKw: -1.5,
    heatKw: 0.5,
    radiatorKw: 1,
    priorityTier: 1,
    services: { medical: 2 },
  }),
  building({ id: "tank", massKg: 1000, powerKw: -0.1, priorityTier: 2 }),
  building({
    id: "comms",
    massKg: 800,
    powerKw: -1,
    heatKw: 0.2,
    radiatorKw: 0.5,
    priorityTier: 2,
    commsRelay: true,
  }),
  building({
    id: "farm",
    massKg: 4000,
    powerKw: -15,
    heatKw: 3,
    radiatorKw: 5,
    priorityTier: 2,
    farm: { areaM2: 90 }, // 2 diets at 45 m²/person
  }),
  building({
    id: "workshop",
    crewOps: { engineer: 1 },
    massKg: 3000,
    powerKw: -10,
    heatKw: 2,
    radiatorKw: 3,
    priorityTier: 3,
    reactions: ["r-parts"],
    reactionKgPerDay: { "r-parts": 40 },
  }),
  building({
    id: "driver",
    massKg: 50000,
    powerKw: -500,
    heatKw: 80,
    radiatorKw: 120,
    priorityTier: 3,
    massDriver: true,
  }),
  building({
    id: "combine",
    crewOps: { engineer: 1 },
    massKg: 40000,
    powerKw: -300,
    heatKw: 60,
    radiatorKw: 90,
    priorityTier: 3,
    reactions: ["r-he3"],
    reactionKgPerDay: { "r-he3": 0.036 },
  }),
  building({
    id: "solar",
    massKg: 1000,
    powerKw: 10,
    powerScalesWithIllumination: true,
    dustSensitive: true,
    wearRatePerYear: 0.05,
  }),
  building({
    id: "battery",
    massKg: 1000,
    powerKw: 0,
    storageKwh: 200,
    storageRoundTripEff: 0.9,
  }),
  building({ id: "fission", massKg: 6000, powerKw: 40, heatKw: 8, wearRatePerYear: 0.05 }),
  building({
    id: "radiator",
    massKg: 800,
    powerKw: -0.2,
    radiatorKw: 15,
    radiatorShared: true,
    priorityTier: 1,
  }),
  building({ id: "industry", massKg: 1000, powerKw: -10, priorityTier: 3 }),
  building({ id: "lab", massKg: 1000, powerKw: -5, priorityTier: 2, sciencePerDay: 10 }),
];

/** 8Ã—8: column x=7 is PSR (class C); x=6 is class A ridge; rest class B flat highland. */
export function makeTestMap(): LunarMap {
  const tiles: Tile[] = [];
  for (let y = 0; y < 8; y++) {
    for (let x = 0; x < 8; x++) {
      tiles.push({
        elevationM: 0,
        illumClass: x === 7 ? "C" : x === 6 ? "A" : "B",
        iceFrac: x === 7 ? 0.056 : 0,
        regolith: "highland",
        slopeDeg: y === 7 ? 20 : 0,
      });
    }
  }
  const def: GameMap = {
    id: "test_map",
    name: "Test Map",
    size: [8, 8],
    tiles: encodeTiles(tiles),
    iceUncertainty: false,
    lavaTubes: [],
    source: "test fixture",
    as_of: AS_OF,
  };
  return loadMap(def);
}

function resource(id: string, storageClass: string): Record<string, unknown> {
  return {
    id,
    name: id,
    phase: 2,
    storageClass,
    densityKgM3: 500,
    boiloffPerDay: 0,
    importCostPerKg: 100000,
    source: "test fixture",
    as_of: AS_OF,
  };
}

export const TEST_RESOURCES = [
  resource("water", "bulk"),
  resource("wastewater", "bulk"),
  resource("o2-gas", "pressurized"),
  resource("co2-gas", "pressurized"),
  resource("h2-gas", "pressurized"),
  resource("ch4-gas", "pressurized"),
  resource("food", "ambient"),
  resource("medkits", "ambient"),
  { ...resource("regolith", "bulk"), groundSourced: true },
  resource("water-ice", "bulk"),
  resource("lox", "cryogenic"),
  resource("metal-slag", "bulk"),
  resource("tailings", "bulk"),
  resource("printed-structure", "ambient"),
  resource("spare-parts", "ambient"),
  resource("machine-components", "ambient"),
  resource("iron", "bulk"),
  resource("he-3", "pressurized"),
];

function reaction(overrides: Record<string, unknown>): Record<string, unknown> {
  return {
    name: overrides["id"],
    energyKwhPerKgPrimary: 1,
    heatKw: 1,
    source: "test fixture",
    as_of: AS_OF,
    ...overrides,
  };
}

export const TEST_REACTIONS = [
  reaction({
    id: "r-ice-extraction",
    building: "oven",
    inputs: [{ resource: "water-ice", kg: 1 }],
    outputs: [{ resource: "water", kg: 1 }],
    primaryOutput: "water",
  }),
  reaction({
    id: "r-electrolysis",
    building: "electro",
    inputs: [{ resource: "water", kg: 1 }],
    outputs: [
      { resource: "o2-gas", kg: 0.89 },
      { resource: "h2-gas", kg: 0.11 },
    ],
    primaryOutput: "o2-gas",
    minTempK: 273,
  }),
  reaction({
    id: "r-mre",
    building: "mre-s",
    inputs: [{ resource: "regolith", kg: 100 }],
    outputs: [
      { resource: "o2-gas", kg: 28 },
      { resource: "metal-slag", kg: 30 },
      { resource: "tailings", kg: 42 },
    ],
    primaryOutput: "o2-gas",
  }),
  reaction({
    id: "r-sabatier",
    building: "sabatier",
    inputs: [
      { resource: "co2-gas", kg: 44 },
      { resource: "h2-gas", kg: 8 },
    ],
    outputs: [
      { resource: "ch4-gas", kg: 16 },
      { resource: "water", kg: 36 },
    ],
    primaryOutput: "water",
  }),
  reaction({
    id: "r-lox",
    building: "cryo",
    inputs: [{ resource: "o2-gas", kg: 1 }],
    outputs: [{ resource: "lox", kg: 1 }],
    primaryOutput: "lox",
  }),
  reaction({
    id: "r-printing",
    building: "printer",
    inputs: [{ resource: "regolith", kg: 1 }],
    outputs: [{ resource: "printed-structure", kg: 1 }],
    primaryOutput: "printed-structure",
  }),
  reaction({
    id: "r-parts",
    building: "workshop",
    inputs: [
      { resource: "iron", kg: 1 },
      { resource: "machine-components", kg: 0.1 },
    ],
    outputs: [{ resource: "spare-parts", kg: 1.1 }],
    primaryOutput: "spare-parts",
  }),
  reaction({
    id: "r-he3",
    building: "combine",
    inputs: [{ resource: "regolith", kg: 100000 }],
    outputs: [
      { resource: "he-3", kg: 0.0015 },
      { resource: "water", kg: 50 },
      { resource: "tailings", kg: 99949.9985 },
    ],
    primaryOutput: "he-3",
  }),
];

export const TEST_TECH = [
  {
    id: "t_basic",
    branch: "T",
    phase: 0,
    trl2026: 8,
    costScience: 10,
    prereqs: [],
    unlocks: { buildings: [], modifiers: [] },
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "t_adv",
    branch: "T",
    phase: 2,
    trl2026: 3,
    costScience: 20,
    prereqs: ["t_basic"],
    unlocks: { buildings: ["gated"], modifiers: [] },
    setbackRisk: 0.5,
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "surface_power_40kw",
    branch: "B",
    phase: 1,
    trl2026: 6,
    costScience: 50,
    prereqs: [],
    unlocks: { buildings: [], modifiers: [] },
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "water_recovery_98",
    branch: "D",
    phase: 3,
    trl2026: 8,
    costScience: 60,
    prereqs: [],
    unlocks: { buildings: [], modifiers: [] },
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "automation_robotics",
    branch: "E",
    phase: 3,
    trl2026: 5,
    costScience: 100,
    prereqs: [],
    unlocks: { buildings: [], modifiers: [] },
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "dust_mitigation",
    branch: "E",
    phase: 2,
    trl2026: 5,
    costScience: 50,
    prereqs: [],
    unlocks: { buildings: [], modifiers: [] },
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "night_landing_nav",
    branch: "A",
    phase: 2,
    trl2026: 6,
    costScience: 40,
    prereqs: [],
    unlocks: { buildings: [], modifiers: [] },
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "precision_landing",
    branch: "A",
    phase: 0,
    trl2026: 8,
    costScience: 20,
    prereqs: [],
    unlocks: { buildings: [], modifiers: [] },
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "orbital_refueling",
    branch: "A",
    phase: 3,
    trl2026: 5,
    costScience: 120,
    prereqs: [],
    unlocks: { buildings: [], modifiers: [] },
    source: "test fixture",
    as_of: AS_OF,
  },
];

export const TEST_EVENTS = [
  {
    id: "micrometeorite",
    category: "environmental",
    rates: { ideal: 5, realistic: 10 }, // inflated vs EVENTS.md for test signal
    conditions: {},
    effects: [{ type: "building-damage", conditionLoss: [0.01, 0.1] }],
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "moonquake",
    category: "environmental",
    rates: { ideal: 2, realistic: 3 },
    conditions: {},
    effects: [{ type: "structural-stress" }],
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "spe-major",
    category: "environmental",
    rates: { ideal: 0.3, realistic: 0.5 },
    warningTicks: [12, 48],
    conditions: { minPhase: 1 },
    effects: [{ type: "radiation-dose", mSv: [100, 500] }],
    alertTemplate: "SPE inbound (ETA {eta} h)",
    source: "test fixture",
    as_of: AS_OF,
  },
  {
    id: "fission-scram",
    category: "technical",
    rates: { ideal: 1, realistic: 2 }, // inflated for test signal
    conditions: {},
    effects: [{ type: "power-outage", ticks: [24, 72] }],
    source: "test fixture",
    as_of: AS_OF,
  },
];

export function makeTestPack(): ContentPack {
  return loadContentPack("test", {
    constants: TEST_CONSTANTS,
    buildings: TEST_BUILDINGS,
    resources: TEST_RESOURCES,
    reactions: TEST_REACTIONS,
    tech: TEST_TECH,
    events: TEST_EVENTS,
  });
}
